name: Weekly Pull Spreads

on:
  schedule:
    - cron: '0 0 * * 1'  # This will run the workflow every Sunday at 00:00

jobs:
  pull_spreads:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pull_spreads.py
      run: python pull_spreads.py
      env:
        ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
