name: Weekly Pull Spreads

on:
  schedule:
    - cron: '0 0 * * 1'  # This will run the workflow every Sunday at 00:00
  workflow_dispatch:

jobs:
  pull_spreads:
    runs-on: ubuntu-latest
    environment: keys
    env:
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
    - name: Check environment variables
      run: |
          echo "ODDS_API_KEY is set: ${{ env.ODDS_API_KEY != '' }}"
          echo "AWS_ACCESS_KEY_ID is set: ${{ env.AWS_ACCESS_KEY_ID != '' }}"
          echo "AWS_SECRET_ACCESS_KEY is set: ${{ env.AWS_SECRET_ACCESS_KEY != '' }}"
          
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pull_odds.py
      run: python pull_odds.py
